'use strict';

const registry = require('../core/Registry');
const loaders = require('../core/MethodLoader');

/**
 * Postman generator - scans every discovered method (init.js metadata,
 * parameter contract, examples.json, responses) and produces a complete
 * Postman v2.1 collection with auth, headers, bodies, query params, examples,
 * variables and environment placeholders. Fully automatic — no manual edits.
 */
function generate(appRoot = process.cwd()) {
  loaders.bootstrap(appRoot);

  const baseUrl = '{{base_url}}';
  const folders = new Map();

  for (const method of registry.listMethods()) {
    const tag = (method.meta.tags && method.meta.tags[0]) || 'General';
    if (!folders.has(tag)) folders.set(tag, { name: tag, item: [] });
    folders.get(tag).item.push(buildItem(method, baseUrl));
  }

  return {
    info: {
      _postman_id: 'rrf-' + Date.now().toString(36),
      name: registry.config.appName || 'RRF API Collection',
      description: 'Auto-generated by RyoForge Runtime Framework',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
    },
    auth: {
      type: 'bearer',
      bearer: [{ key: 'token', value: '{{access_token}}', type: 'string' }],
    },
    variable: [
      { key: 'base_url', value: 'http://localhost:3000' },
      { key: 'access_token', value: '' },
      { key: 'api_key', value: '' },
    ],
    item: [...folders.values()],
  };
}

function buildItem(method, baseUrl) {
  const params = method.getParameter();
  const segments = method.route.split('/').filter(Boolean);
  const queryParams = [];
  const bodyFields = {};
  const headers = [{ key: 'Content-Type', value: 'application/json' }];

  for (const [name, ruleRaw] of Object.entries(params)) {
    const rule = typeof ruleRaw === 'string' ? { type: ruleRaw } : ruleRaw;
    const where = rule.in || (method.requestMethods.includes('GET') ? 'query' : 'body');
    if (where === 'query') {
      queryParams.push({ key: name, value: String(rule.example ?? ''), description: rule.description || rule.type });
    } else if (where === 'header') {
      headers.push({ key: name, value: String(rule.example ?? '') });
    } else {
      bodyFields[name] = rule.example ?? exampleFor(rule.type);
    }
  }

  if (method.meta.isSecured && method.meta.auth === 'apikey') {
    headers.push({ key: 'x-api-key', value: '{{api_key}}' });
  }

  const example = method.examples?.request || bodyFields;

  return {
    name: method.name,
    request: {
      method: method.requestMethods[0] || 'POST',
      header: headers,
      ...(Object.keys(example).length
        ? { body: { mode: 'raw', raw: JSON.stringify(example, null, 2), options: { raw: { language: 'json' } } } }
        : {}),
      url: {
        raw: baseUrl + method.route + (queryParams.length ? '?' + queryParams.map((q) => `${q.key}=${q.value}`).join('&') : ''),
        host: [baseUrl],
        path: segments,
        ...(queryParams.length ? { query: queryParams } : {}),
      },
      description: method.meta.description || method.meta.summary || '',
    },
    response: buildResponseExamples(method),
  };
}

function buildResponseExamples(method) {
  const responses = method.getResponses();
  const out = [];
  for (const [key, sample] of Object.entries(responses || {})) {
    const def = registry.responses[key] || { responseCode: 200, responseMessage: { en: key } };
    out.push({
      name: key,
      status: 'OK',
      code: typeof def.responseCode === 'number' && def.responseCode < 600 ? def.responseCode : 200,
      header: [{ key: 'Content-Type', value: 'application/json' }],
      body: JSON.stringify(
        {
          responseCode: def.responseCode,
          responseMessage: def.responseMessage.en || key,
          responseData: sample || {},
        },
        null,
        2
      ),
    });
  }
  return out;
}

function exampleFor(type) {
  return {
    string: 'string', email: 'user@example.com', uuid: '00000000-0000-0000-0000-000000000000',
    number: 0, integer: 0, boolean: true, date: new Date().toISOString(), array: [], object: {},
  }[type] ?? 'string';
}

module.exports = { generate };
